### ISSUE TITLE
Getting dumped back to BASIC when using file selector on BDOS records

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#10]
When navigating records I am  getting dumped back to BASIC with a Statement Doesn't Exist error.

From a base record (in my case 62 where the player is) single stepping up or down 18 times causes it to happen.

**Comment by stefandrissen** [comment]
Thanks, I had seen this occur now and then but had not taken the time to look closer. The nice easy reproducible 18 changes was enough to quickly spot the stack growing two bytes per change. Fixed in 2.33.
