### ISSUE TITLE
Demo: Keypresses in the demo player very very bouncy

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#13]
Using keys in the demo are very bouncy, trying to un-pause is especially hit and miss

**Comment by stefandrissen** [comment]
The code is performing a simple press and release checks, when press is registered, it is kept registered until key released. I do not recall this being an issue back in the day on real hardware.
With SimCoupe I have no issue - although this may not be all too fair.
Is your membrane ok?

**Comment by dandoore** [comment]
Membrane is fine - first thing I looked it - I will compare behaviour with V2.10 when I'm back close to the real hardware

**Comment by dandoore** [comment]
Ok, so 2.10 is pretty much the same (some keypresses get missed occasionally) but I'm refining the report to say it's OK pressing keys but when you get to pause... It's happy to pause from running nearly every time but it's the unpause that seems to be the problem as in I have to press up to 10 times for it to do that, same in V2.10.
