### ISSUE TITLE
Loader: Record number displaying as incorrect

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#16]
When showing records in the 100's where middle digit is a zero:

Reproduction:
Start at Record 99
Move to 100 - shows 10
Move to 101 - shows 11
Same when stepping up to 109 (showing as 19)
Move from 109 to 110 - now shows 110

Same when at 199 -> 210

**Comment by stefandrissen** [comment]
Well that was embarrassing, I wanted to blame a younger me, but this quickly cobbled together code was cobbled together a bit too quickly.
