### ISSUE TITLE
Enable GitHub Wiki and import manual

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#17]
Enable Wiki and import the instaructions from https://www.worldofsam.org/products/sam-mod-player ?

**Comment by stefandrissen** [comment]
Imported and heavily redacted, I was planning on only including:

F9 performs reset

But then I saw that this was already in the manual and that you forgot to RTFM before creating #14 🤪

**Comment by dandoore** [comment]
You could argue that extracting it was my penance for #14 - and it was :-)
