### ISSUE TITLE
Soundtracker 2.3 was first with 31 samples, not 2.2

### ISSUE THREAD

**Issue by stefandrissen** [stefandrissen/SAM-MOD-player#18]
https://github.com/cmatsuoka/tracker-history/issues/5

fix: https://github.com/stefandrissen/SAM-MOD-player/blob/9a47003a3414fd14b056846b86c67748290918de/src/loader/mod.s#L24-L25

**Comment by TCH68k** [comment]
How would it determine which type it loads? If 2.2 would be able to handle the 31 sampled modules without the M.K. signature, then it would mean, that it can only handle 31 sampled modules. But if you check the images on pouet.net:

https://content.pouet.net/files/screenshots/00048/00048007.jpg
https://content.pouet.net/files/screenshots/00034/00034741.png

you can see, that 2.2 has one digit for samples and 2.3 has two.

**Comment by stefandrissen** [comment]
As stated, I was led down a rabbit hole by some MOD format history document claiming 2.2 supported 31 samples without M.K. 
Based on your comment, this claim seems false

My player performs sanity checks on the file contents, the easiest one being the presence of a signature like M.K. / FLT4 / M!K!. 
If there is no signature, the sample headers are checked for sanity.
If there are more than 15 valid sample headers, I classed it as 2.2. 

Thankfully this is nonsense.

**Comment by TCH68k** [comment]
I see. Sanity check can work, but i doubt Soundtracker 2.2 (or ANY Sound/Noise/ProTracker) did that. :)
