### ISSUE TITLE
Bug in comment

### ISSUE THREAD

**Issue by AntonyDTA** [stefandrissen/SAM-MOD-player#31]
https://github.com/stefandrissen/SAM-MOD-player/blob/dcb2b66aa441da35df4452989c5fa4c1104e209f/src/tracker/install.mod.s#L162
; 0 = no sample

**Comment by stefandrissen** [comment]
:-) Thanks - fixed in https://github.com/stefandrissen/SAM-MOD-player/commit/e82b272ddde88b00c86d28bd19ac00b2e1244ec0
