### ISSUE TITLE
When booting from BDOS HDD with no floppy file selector locks up

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#8]
When booting from BDOS HDD with no floppy attached the file selector locks up as I presume it's expecting a floppy drive?

**Comment by dandoore** [comment]
Also if the drive is empty it just keeps waiting until a disk is inserted - maybe on a 2 drive system (or mass storage) it should just time out back to the selector?

**Comment by stefandrissen** [comment]
Nice catch. That's the read sector hook code for you. I'll update the loader to default to mass storage if records detected.
