### ISSUE TITLE
BDOS record access by number/browser in file selector

### ISSUE THREAD

**Issue by dandoore** [stefandrissen/SAM-MOD-player#9]
I foolishly have all my MOD files at about record 191 - any way of being able to select a record in a file browser of go to it by number?

**Comment by stefandrissen** [comment]
I was thinking about this too while browsing the demo package at https://sam.speccy.cz/demo.html, which has mods starting at record 50 or so.

The file browser is very basic and fine for floppy disks. The mass storage record handling was bolted on using mainly existing functionality.

My knee jerk reaction is to add symbol+cursor to jump 10 records, with maybe shift+cursor to jump 100 records?

**Comment by dandoore** [comment]
That works for me, although having Shift jump in 10's, Symbol 100's makes more sense to me but hey, I'll take anything other than single stepping :-)

**Comment by stefandrissen** [comment]
OK, I've implemented a buggy version. So it's like the nineties all over again and I'm having to listen to all the mods I run into while reaching the boundaries. :-)

**Comment by dandoore** [comment]
That works a treat :-)
